# packages/seisai-dataset/pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-dataset"
version = "0.1.0"
description = "SEG-Y gather dataset toolkit for pytorch"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = [
  "numpy",
  "scipy",
  "torch",
  "segyio",
  "seisai-pick>=0.1.0",
  "seisai-transforms>=0.1.0"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_dataset*"]
