base: base_mae_optim_v2.yaml

paths:
  out_dir: ../runs/opt_v2_T01_adamw_timm_fbbnF_lr5e-4_wd1e-2

tracking:
  exp_name: opt_v2_T01_adamw_timm_fbbnF_lr5e-4_wd1e-2

train:
  lr: 5.0e-4
  weight_decay: 1.0e-2

optimizer:
  name: adamw
  filter_bias_and_bn: false
  kwargs: {}
