base: base_mae_optim_v2.yaml

paths:
  out_dir: ../runs/opt_v2_T07_adan_lr5e-4_wd1e-2

tracking:
  exp_name: opt_v2_T07_adan_lr5e-4_wd1e-2

train:
  lr: 5.0e-4
  weight_decay: 1.0e-2

optimizer:
  name: adan
  filter_bias_and_bn: true
  kwargs: {}
