base: base_mae_optim_v2.yaml

paths:
  out_dir: ../runs/opt_v2_T11_lamb_lr1e-3_wd1e-2

tracking:
  exp_name: opt_v2_T11_lamb_lr1e-3_wd1e-2

train:
  lr: 1.0e-3
  weight_decay: 1.0e-2

optimizer:
  name: lamb
  filter_bias_and_bn: true
  kwargs: {}
