base: base_blindtrace.yaml

paths:
  out_dir: ../runs/prestage_B1

tracking:
  exp_name: prestage_B1

model:
  backbone: resnet18
  pretrained: false
  pre_stage_use_bn: true
  pre_stages: 1
  pre_stage_strides:
  - - 1
    - 2
  pre_stage_channels:
  - 16
  pre_stage_kernels:
  - 3
  pre_stage_antialias: false
