paths:
  segy_files: train_sgy_drop005_iter1.txt
  phase_pick_files: train_fb_drop005_iter1.txt
  infer_segy_files: train_sgy_drop005_iter1.txt
  infer_phase_pick_files: train_fb_drop005_iter1.txt
  out_dir: ./runs/prestage2_drop005
base: base_psn.yaml

model:
  pre_stage_use_bn: true
  pre_stages: 2
  pre_stage_strides:
  - - 1
    - 1
  - - 1
    - 1
  pre_stage_channels:
  - 16
  - 16
  pre_stage_kernels:
  - 3
  - 3
  pre_stage_antialias: false

tracking:
  exp_name: prestage2_drop005

