[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-pick"
version = "0.1.0"
description = "seismic event pick algo + detectors"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
  "numpy",
  "numba>=0.57",   # STALTAが@njit依存
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_pick*"]
