paths:
  segy_files:
    - ./_artifacts/blindtrace_demo_input.sgy
  out_dir: ./_blindtrace_infer_out

infer:
  ckpt_path: ./_artifacts/blindtrace_demo_ckpt.pt
  device: auto
  out_suffix: _pred.sgy
  overwrite: true
  sort_within: chno
  ffids: null
  allow_unsafe_override: false
  note: demo

tile:
  tile_h: 64
  overlap_h: 16
  tile_w: 512
  overlap_w: 64
  tiles_per_batch: 4
  amp: true
  use_tqdm: false

cover:
  mask_ratio: 0.5
  band_width: 1
  noise_std: 1.0
  mask_noise_mode: replace
  use_amp: true
  offsets: [0]
  passes_batch: 4
