[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-transforms"
version = "0.1.0"
requires-python = ">=3.10"
description = "Signal & seismic transforms for SeisAI"
license = {text = "MIT"}
dependencies = [
  "numpy",
  "torch",
  "scipy",
  "seisai-utils>=0.1.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_transforms*"]
