# packages/seisai_utils/pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seisai-utils"
version = "0.1.0"
requires-python = ">=3.9"
license = {text = "MIT"}
[tool.setuptools]
package-dir = {"" = "src"}
dependencies = [
  "yaml",
]
[tool.setuptools.packages.find]
where = ["src"]
include = ["seisai_utils*"]
