base: psn_D3.yaml

paths:
  out_dir: ../runs/psn_D3_backbone_convnext_tiny_frommae

tracking:
  exp_name: psn_D3_backbone_convnext_tiny_frommae

model:
  backbone: convnext_tiny

train:
  init_ckpt: ../../mae/runs/backbone_D3_convnext_tiny/ckpt/best.pt
