base: base_psn.yaml

paths:
  out_dir: ../runs/psn_C1

tracking:
  exp_name: psn_C1

model:
  pre_stages: 2
  pre_stage_strides:
    - [1, 1]
    - [1, 2]
  pre_stage_channels: [16, 16]
  pre_stage_kernels: [3, 3]
  pre_stage_antialias: false

train:
  init_ckpt: ../../mae/runs/prestage_C1/ckpt/best.pt
